# Generated by Django 3.2.6 on 2021-08-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('heading1', models.CharField(max_length=30)),
                ('h1content', models.CharField(max_length=1000)),
                ('heading2', models.CharField(max_length=30)),
                ('h2content', models.CharField(max_length=1000)),
                ('Timestamp', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
