# Generated by Django 3.2.6 on 2021-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h1content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='h2content',
            field=models.TextField(),
        ),
    ]
