# Generated by Django 3.2.6 on 2021-08-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210812_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h2content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading2',
            field=models.CharField(default='', max_length=30),
        ),
    ]
