# Generated by Django 3.2.6 on 2021-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20210815_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_reply',
            name='comment_sno',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
