# Generated by Django 3.2.6 on 2021-08-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_comment_reply_comment_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='h1content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h2content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading2',
        ),
    ]
