# Generated by Django 3.2.5 on 2021-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210815_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='h1content',
        ),
        migrations.AddField(
            model_name='post',
            name='h1heading',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='h2content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='h2heading',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
    ]
