# Generated by Django 3.2.5 on 2021-08-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20210830_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='shop/images', upload_to='shop/images'),
        ),
    ]
