# Generated by Django 3.2.5 on 2021-08-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
