# Generated by Django 3.2.5 on 2021-08-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_track'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_track',
        ),
    ]
